[project]
name = "telekinesis"
version = "0.1.0"

[[targets]]
type = "gpui"
id = "gui"
path = "ui/gui"

[[targets]]
type = "tui"
id = "tui"
path = "ui/tui"

[[targets]]
type = "native"
id = "mobile"
path = "apps/mobile"
